version: '3.8'

services:
  node-app:
    image: node-web
    container_name: cu-web
    command: "node -v"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    ports:
      - "3000:3000"
    restart: always

